services:
  mysql:
    image: mysql:9.3
    container_name: ebank-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - ebank_network
    volumes:
      - ./scripts/mysql/init:/docker-entrypoint-initdb.d
      
  rabbitmq:
    image: rabbitmq:4-management
    container_name: ebank-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: P4ssword!
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ebank_network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      - mysql
        
  configserver:
    image: "examplebank/configserver:latest"
    container_name: ebank-configserver
    environment:
      SPRING_CLOUD_CONFIG_GIT_URI: "https://github.com/mrschwartx/demo-spring-microservices.git"
      SPRING_CLOUD_CONFIG_GIT_SEARCH_PATH: "configs"
    ports:
      - "8071:8071"
    networks:
      - ebank_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: ./scripts/docker/common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "examplebank/eurekaserver:latest"
    container_name: ebank-eurekaserver
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
    ports:
      - "8070:8070"
    networks:
      - ebank_network
    depends_on:
      configserver:
        condition: service_healthy

  loans:
    image: "examplebank/loans:latest"
    container_name: ebank-loans
    environment:
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_SERVICE_URL: "http://eurekaserver:8070/eureka/"
      LOANS_JDBC_DATABASE_URL: "jdbc:mysql://mysql:3306/ebank_loans_db?serverTimezone=Asia/Jakarta"
      LOANS_JDBC_DATABASE_USERNAME: "loans_user"
      LOANS_JDBC_DATABASE_PASSWORD: "loans_pass"
    ports:
      - "8090:8090"
    networks:
      - ebank_network
    depends_on:
      configserver:
        condition: service_healthy

  accounts:
    image: "examplebank/accounts:latest"
    container_name: ebank-accounts
    environment:
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_SERVICE_URL: "http://eurekaserver:8070/eureka/"
      ACCOUNTS_JDBC_DATABASE_URL: "jdbc:mysql://mysql:3306/ebank_accounts_db?serverTimezone=Asia/Jakarta"
      ACCOUNTS_JDBC_DATABASE_USERNAME: "accounts_user"
      ACCOUNTS_JDBC_DATABASE_PASSWORD: "accounts_pass"
    ports:
      - "8080:8080"
    networks:
      - ebank_network
    depends_on:
      configserver:
        condition: service_healthy

  cards:
    image: "examplebank/cards:latest"
    container_name: ebank-cards
    environment:
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_SERVICE_URL: "http://eurekaserver:8070/eureka/"
      CARDS_JDBC_DATABASE_URL: "jdbc:mysql://mysql:3306/ebank_cards_db?serverTimezone=Asia/Jakarta"
      CARDS_JDBC_DATABASE_USERNAME: "cards_user"
      CARDS_JDBC_DATABASE_PASSWORD: "cards_pass"
    ports:
      - "9000:9000"
    networks:
      - ebank_network
    depends_on:
      configserver:
        condition: service_healthy
  
  gatewayserver:
    image: "examplebank/gatewayserver:latest"
    container_name: ebank-gatewayserver
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_SERVICE_URL: "http://eurekaserver:8070/eureka/"
    ports:
      - "8072:8072"
    networks:
      - ebank_network
    depends_on:
      configserver:
        condition: service_healthy

networks:
  ebank_network:
    driver: "bridge"
