services:
  mysql:
    image: mysql:9.3
    container_name: ebank-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql/init:/docker-entrypoint-initdb.d
