services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: P4ssword!
    ports:
      - 5672:5672
      - 15672:15672
  
  mysql:
    image: mysql:9.3
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql/init:/docker-entrypoint-initdb.d
