server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_GIT_URI:https://github.com/mrschwartx/demo-spring-microservices.git}
          default-label: main
          timeout: 5
          clean-on-start: true
          force-pull: true
          search-paths: ${SPRING_CLOUD_CONFIG_GIT_SEARCH_PATH:configs}
          # native:
          # search-locations: "classpath:/config"
          # search-locations: "file://~/config"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    com:
      example:
        configserver: DEBUG
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{trace_id:-},%X{span_id:-}] [%t] %c{1} - %m%n"
    console: "%d{HH:mm:ss.SSS} %5p [${spring.application.name},%X{trace_id:-},%X{span_id:-}] [%t] %c{1} - %m%n"
encrypt:
  key: "MySup3r$tr0ngK3y123!"
