spring:
  config:
    active:
      on-profile: "qa"
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/ebank_cards_db?serverTimezone=Asia/Jakarta}
    username: ${JDBC_DATABASE_USERNAME:e23518fef6e0d53f29ef12ca9830cff7c7f8b35589d86a12c2efe4249a64b74c}
    password: ${JDBC_DATABASE_PASSWORD:cf8dbeb300a11cc0d443596b570580291d7213114cd2c3d6ddc5480a2e8da7d1}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:32a056e28ea44a8ba8def5ac6d3a4a4e748bcaaabb6f128824654f1ac324c3a4}
    password: ${RABBITMQ_PASSWORD:671bbfa0f6512f8c8a9ece3ea7df92466dc3f0e99845b6f05fc7b056e83776e0}