spring:
  config:
    active:
      on-profile: "qa"
  datasource:
    url: ${ACCOUNTS_JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/ebank_accounts_db?serverTimezone=Asia/Jakarta}
    username: ${ACCOUNTS_JDBC_DATABASE_USERNAME:accounts_user}
    password: ${ACCOUNTS_JDBC_DATABASE_PASSWORD:accounts_pass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: rabbitmq
    password: P4ssword
