server:
  port: 8080
spring:
  application:
    name: "accounts"
  config:
    import:
      - "accounts_qa.yml"
      - "accounts_prod.yml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0.0"