server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: "accounts"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - "accounts_qa.yml"
      - "accounts_prod.yml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0.0"