spring:
  config:
    active:
      on-profile: "qa"
  datasource:
    url: ${CARDS_JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/ebank_cards_db?serverTimezone=Asia/Jakarta}
    username: ${CARDS_JDBC_DATABASE_USERNAME:cards_user}
    password: ${CARDS_JDBC_DATABASE_PASSWORD:cards_pass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
