server:
  port: 9000
  shutdown: graceful
spring:
  application:
    name: "cards"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - "cards_qa.yml"
      - "cards_prod.yml"
build:
  version: "1.0.0"
