server:
  port: 9000
spring:
  application:
    name: "cards"
  config:
    import:
      - "cards_qa.yml"
      - "cards_prod.yml"
  profiles:
    active:
      - "qa"
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0.0"
