server:
  port: 8090
spring:
  application:
    name: "loans"
  config:
    import:
      - "loans_qa.yml"
      - "loans_prod.yml"
  profiles:
    active:
      - "qa"
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0.0"