server:
  port: 8090
  shutdown: graceful
spring:
  application:
    name: "loans"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - "loans_qa.yml"
      - "loans_prod.yml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0.0"