spring:
  config:
    active:
      on-profile: "qa"
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/ebank_cards_db?serverTimezone=Asia/Jakarta}
    username: ${JDBC_DATABASE_USERNAME:1578fe8c89076d0b127f27561bf695ab76739c502ad71dea956003641a9e131b}
    password: ${JDBC_DATABASE_PASSWORD:7baca123815046de76ce032970feed8fc8e80a25d05d1b506ab0b87a4adb5277}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:32a056e28ea44a8ba8def5ac6d3a4a4e748bcaaabb6f128824654f1ac324c3a4}
    password: ${RABBITMQ_PASSWORD:671bbfa0f6512f8c8a9ece3ea7df92466dc3f0e99845b6f05fc7b056e83776e0}